In [1]:
import tensorflow as tf
import seaborn as sns
import numpy as np

from PIL import Image
import glob
from collections import defaultdict
from tensorflow import keras
from tensorflow.keras import layers

/home/apiiit-rkv/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/apiiit-rkv/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/apiiit-rkv/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/apiiit-rkv/anaconda3/lib/python3.7/site-packages/tensorflow/pyth

In [2]:
IMG_SIZE = (64,64)
def pixels_from_path(file_path):
    im = Image.open(file_path)
    im = im.resize(IMG_SIZE)
    np_im = np.array(im)
    #matrix of pixel RGB values
    return np_im

In [3]:
glob.glob('/home/apiiit-rkv/Desktop/TRAIN/*')

['/home/apiiit-rkv/Desktop/TRAIN/horse-116.jpg',
 '/home/apiiit-rkv/Desktop/TRAIN/dog.60.jpg',
 '/home/apiiit-rkv/Desktop/TRAIN/horse-20.jpg',
 '/home/apiiit-rkv/Desktop/TRAIN/horse-68.jpg',
 '/home/apiiit-rkv/Desktop/TRAIN/dog.53.jpg',
 '/home/apiiit-rkv/Desktop/TRAIN/horse-78.jpg',
 '/home/apiiit-rkv/Desktop/TRAIN/dog.43.jpg',
 '/home/apiiit-rkv/Desktop/TRAIN/horse-24.jpg',
 '/home/apiiit-rkv/Desktop/TRAIN/horse-85.jpg',
 '/home/apiiit-rkv/Desktop/TRAIN/horse-52.jpg',
 '/home/apiiit-rkv/Desktop/TRAIN/dog.113.jpg',
 '/home/apiiit-rkv/Desktop/TRAIN/dog.97.jpg',
 '/home/apiiit-rkv/Desktop/TRAIN/horse-100.jpg',
 '/home/apiiit-rkv/Desktop/TRAIN/dog.66.jpg',
 '/home/apiiit-rkv/Desktop/TRAIN/horse-98.jpg',
 '/home/apiiit-rkv/Desktop/TRAIN/dog.37.jpg',
 '/home/apiiit-rkv/Desktop/TRAIN/horse-7.jpg',
 '/home/apiiit-rkv/Desktop/TRAIN/dog.84.jpg',
 '/home/apiiit-rkv/Desktop/TRAIN/dog.48.jpg',
 '/home/apiiit-rkv/Desktop/TRAIN/horse-48.jpg',
 '/home/apiiit-rkv/Desktop/TRAIN/horse-57.jpg',
 '/home/

In [4]:
shape_counts = defaultdict(int)
for i, cat in enumerate(glob.glob('/home/apiiit-rkv/Desktop/tot/tottrain/dog/*')[:1000]):
    if i%100==0:
        print(i)
    img_shape = pixels_from_path(cat).shape
    shape_counts[str(img_shape)]= shape_counts[str(img_shape)]+ 1

0
100


In [5]:
shape_items = list(shape_counts.items())
shape_items.sort(key = lambda x: x[1])
shape_items.reverse()

In [6]:
# 10% of the data will automatically be used for validation
validation_size = 0.1
img_size = IMG_SIZE # resize images to be 374x500 (most common shape)
num_channels = 3 # RGB
sample_size = 8192 #We'll use 8192 pictures (2**13)

In [7]:
len(glob.glob('/home/apiiit-rkv/Desktop/tot/tottrain/dog/*'))

120

In [8]:
pixels_from_path(glob.glob('/home/apiiit-rkv/Desktop/tot/tottrain/dog/*')[5]).shape

(64, 64, 3)

In [9]:
SAMPLE_SIZE = 120
#print("loading trainin cat images...")
#cat_train_set = np.asarray([pixels_from_path(cat) for cat in glob.glob('/home/apiiit-rkv/Desktop/tot/tottrain/horse/*')[:SAMPLE_SIZE]])
print("loading training dog images...")
dog_train_set = np.asarray([pixels_from_path(dog) for dog in glob.glob('/home/apiiit-rkv/Desktop/tot/tottrain/dog/*')[:SAMPLE_SIZE]])

loading training dog images...


In [10]:
valid_size = 34
print("loading validation dog images...")
dog_valid_set = np.asarray([pixels_from_path(cat) for cat in glob.glob('/home/apiiit-rkv/Desktop/tot/tottest/dog/*')[-valid_size:]])


loading validation dog images...


In [11]:
x_train = np.concatenate([dog_train_set])
#labels_train = np.asarray([1 for _ in range(SAMPLE_SIZE)]+[0 for _ in range(SAMPLE_SIZE)])
labels_train = np.asarray([1 for _ in range(SAMPLE_SIZE)])
print(labels_train.shape)

(120,)


In [12]:
x_valid = np.concatenate([ dog_valid_set])
labels_valid = np.asarray([1 for _ in range(valid_size)])
print(labels_valid.shape)

(34,)


In [13]:
x_train.shape

(120, 64, 64, 3)

In [14]:
labels_train.shape

(120,)

In [15]:
labels_valid.shape

(34,)

# Run of the Mill MLP

In [16]:
from tensorflow import keras
from tensorflow.keras import layers

total_pixels = img_size[0] *img_size[1] * 3
fc_size = 512

inputs = keras.Input(shape=(img_size[1], img_size[0],3), name='ani_image')
x = layers.Flatten(name = 'flattened_img')(inputs) #turn image to vector.

x = layers.Dense(fc_size, activation='relu', name='first_layer')(x)
outputs = layers.Dense(1, activation='sigmoid', name='class')(x)

model = keras.Model(inputs=inputs, outputs=outputs)

In [17]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense, Dropout, Activation
from tensorflow.keras.preprocessing.image import ImageDataGenerator
model2=Sequential()
input_shape=(64,64,3)
model2 = Sequential(layers=[
    # input layers and convolutional layers
    Conv2D(128, kernel_size=(3,3), activation='relu', input_shape=input_shape),
    MaxPooling2D(pool_size=(2,2)),
    Conv2D(256, kernel_size=(3,3), activation='relu'),
    MaxPooling2D(pool_size=(2,2))
])


In [18]:
shape_counts = defaultdict(int)
for i, cat in enumerate(glob.glob('/home/apiiit-rkv/Desktop/tot/tottrain/horse/*')[:1000]):
    if i%100==0:
        print(i)
    img_shape = pixels_from_path(cat).shape
    shape_counts[str(img_shape)]= shape_counts[str(img_shape)]+ 1

In [19]:
shape_items = list(shape_counts.items())
shape_items.sort(key = lambda x: x[1])
shape_items.reverse()

In [20]:
validation_size = 0.1
img_size = IMG_SIZE # resize images to be 374x500 (most common shape)
num_channels = 3 # RGB
sample_size = 8192 

In [21]:
len(glob.glob('/home/apiiit-rkv/Desktop/tot/tottrain1/horse/*'))

120

In [22]:
pixels_from_path(glob.glob('/home/apiiit-rkv/Desktop/tot/tottrain1/horse/*')[5]).shape

(64, 64, 3)

In [23]:
SAMPLE_SIZE = 120
#print("loading trainin cat images...")
#cat_train_set = np.asarray([pixels_from_path(cat) for cat in glob.glob('/home/apiiit-rkv/Desktop/tot/tottrain/horse/*')[:SAMPLE_SIZE]])
print("loading training horseimages...")
horse_train_set = np.asarray([pixels_from_path(horse) for horse in glob.glob('/home/apiiit-rkv/Desktop/tot/tottrain1/horse/*')[:SAMPLE_SIZE]])

loading training horseimages...


In [24]:
valid_size = 34
print("loading validation horseimages...")
horse_valid_set = np.asarray([pixels_from_path(horse) for horse in glob.glob('/home/apiiit-rkv/Desktop/tot/tottest1/horse/*')[-valid_size:]])


loading validation horseimages...


In [25]:
x_train1 = np.concatenate([horse_train_set])
#labels_train = np.asarray([1 for _ in range(SAMPLE_SIZE)]+[0 for _ in range(SAMPLE_SIZE)])
labels_train1 = np.asarray([0 for _ in range(SAMPLE_SIZE)])
print(labels_train1)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0]


In [26]:
x_valid1 = np.concatenate([ horse_valid_set])
labels_valid1 = np.asarray([0 for _ in range(valid_size)])
print(labels_valid1.shape)
print(labels_valid1)


(34,)
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


In [27]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense, Dropout, Activation
from tensorflow.keras.preprocessing.image import ImageDataGenerator
model1=Sequential()
input_shape=(64,64,3)
model1 = Sequential(layers=[
    # input layers and convolutional layers
    Conv2D(128, kernel_size=(3,3), activation='relu', input_shape=input_shape),
    MaxPooling2D(pool_size=(2,2)),
    Conv2D(256, kernel_size=(3,3), activation='relu'),
    MaxPooling2D(pool_size=(2,2))
])


In [28]:
import keras
print(keras.__version__)
from tensorflow.keras.layers import concatenate
from tensorflow.keras.models import Model, Sequential
from tensorflow.keras.layers import Dense, Input

2.3.1


Using TensorFlow backend.


In [29]:
model_concat = concatenate([model1.output, model2.output], axis=-1)

In [30]:
model_concat= Flatten()(model_concat)
model_concat = Dense(1, activation='softmax')(model_concat)
model = Model(inputs=[model1.input, model2.input], outputs=model_concat)

In [31]:
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [32]:
model.summary()

Model: "model_1"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
conv2d_2_input (InputLayer)     [(None, 64, 64, 3)]  0                                            
__________________________________________________________________________________________________
conv2d_input (InputLayer)       [(None, 64, 64, 3)]  0                                            
__________________________________________________________________________________________________
conv2d_2 (Conv2D)               (None, 62, 62, 128)  3584        conv2d_2_input[0][0]             
__________________________________________________________________________________________________
conv2d (Conv2D)                 (None, 62, 62, 128)  3584        conv2d_input[0][0]               
____________________________________________________________________________________________

In [33]:
#fitted_model = model.fit([x_train,x_train1],
                        steps_per_epoch = 5,
                        epochs = 5,
                        validation_data = [x_valid,x_valid1],
                        validation_steps = 1000)

IndentationError: unexpected indent (<ipython-input-33-d0007e11bc2f>, line 2)

In [34]:
print(labels_train)
print(labels_valid)
print(labels_train1)
print(labels_valid1)

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1]
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


In [35]:
from numpy  import *   
out_u=matrix(np.zeros(120))
out_sig=matrix(np.ones(120))
out_both = concatenate([out_u, out_sig], axis=1)
print(out_both)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [36]:
SAMPLE_SIZE=60
labels_train = np.asarray([1 for _ in range(SAMPLE_SIZE)]+[0 for _ in range(SAMPLE_SIZE)])
print(labels_train.shape)
print(labels_train)

(120,)
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0]


In [37]:
labels_train.shape

(120,)

In [38]:
SAMPLE_SIZE=17
labels_valid = np.asarray([1 for _ in range(SAMPLE_SIZE)]+[0 for _ in range(SAMPLE_SIZE)])
print(labels_valid)

print(labels_valid.shape)

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
(34,)


In [41]:

out_both = concatenate([x_train, x_train1], axis=1, name = 'concatenate')
out_both1 = concatenate([x_valid, x_valid1], axis=1, name = 'concatenate')

TypeError: concatenate() got an unexpected keyword argument 'name'

In [ ]:
epoch=10
history = model.fit([x_train,x_train1],
                    [labels_train],
                    shuffle = True, #important since we loaded cats first, dogs second.
                    epochs=10,
                    validation_data=([x_valid,x_valid1], labels_valid))


Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
Train on 120 samples, validate on 34 samples
Epoch 1/10
 32/120 [=======>......................] - ETA: 42s - loss: 7.6666 - accuracy: 0.5000

In [190]:
14*14

196

In [223]:
x_train = np.concatenate([dog_train_set, horse_train_set])
labels_train = np.asarray([1 for _ in range(SAMPLE_SIZE)]+[0 for _ in range(SAMPLE_SIZE)])
x_valid = np.concatenate([dog_valid_set, horse_valid_set])
labels_valid = np.asarray([1 for _ in range(valid_size)]+[0 for _ in range(valid_size)])
print(labels_valid)

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


In [222]:
history = model.fit(x_train, 
                    labels_train,
                    batch_size=32, 
                    shuffle = True, #important since we loaded cats first, dogs second.
                    epochs=10,
                    validation_data=(x_valid, labels_valid))

ValueError: Error when checking model input: the list of Numpy arrays that you are passing to your model is not the size the model expected. Expected to see 2 array(s), but instead got the following list of 1 arrays: [array([[[[112, 135, 127],
         [114, 137, 129],
         [108, 131, 123],
         ...,
         [114, 132, 132],
         [112, 130, 130],
         [113, 131, 131]],

        [[107, 130, 122],
 ...